const collections = {
  doctors: "/doctors",
};

enum HoraireData {
  placeholder = "Lundi : de 9h00 à 12h30 - 14h30 à 19h00                                             Mardi : de 9h00 à 12h30 - 14h30 à 19h00                                          Mercredi : de 9h00 à 12h30 - 14h30 à 19h00                                         Jeudi : de 9h00 à 12h30 - 14h30 à 19h00                                           Vendredi : de 9h00 à 12h30 - 14h30 à 19h00                                          Samedi : Fermé                                                 Dimanche : Fermé",
}

const VilleData = [
  "Agadir",
  "Al Hoceima",
  "Asilah",
  "Azilal",
  "Béni Mellal",
  "Benslimane",
  "Berkane",
  "Boujdour",
  "Casablanca",
  "Chefchaouen",
  "Dakhla",
  "El Jadida",
  "Errachidia",
  "Es Semara",
  "Essaouira",
  "Es-Semara",
  "Fés",
  "Guelmim",
  "Ifrane",
  "Kasba-Tadla",
  "Kelâat Es-Sraghna",
  "Kénitra",
  "Khémisset",
  "Khénifra",
  "Khouribga",
  "Laâyoune",
  "Larache",
  "Marrakech",
  "Mediouna",
  "Meknès",
  "Midelt",
  "Mohammédia",
  "Nador",
  "Nouasseur",
  "Ouarzazate",
  "Oujda",
  "Rabat",
  "Safi",
  "Salé",
  "Sefrou",
  "Settat",
  "Sidi Ifni",
  "Sidi Kacem",
  "Tanger",
  "TanTan",
  "Taounate",
  "Taourirt",
  "Taroudant",
  "Taza",
  "Témara",
  "Tétouan",
  "Tiznit",
  "Zagora",
];

export { collections, HoraireData, VilleData };
